//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3062.0.
// 
namespace Virinco.WATS.Converter.SigmaQuest
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class UnitReport
    {

        private Station stationField;

        private Operator operatorField;

        private Category categoryField;

        private Property propertyField;

        private TestRun testRunField;

        private string modeField;

        private System.DateTimeOffset starttimeField;

        private System.DateTimeOffset endtimeField;

        private bool endtimeFieldSpecified;

        private string versionField;

        private long quantityField;

        private bool quantityFieldSpecified;

        private string softwareversionField;

        private bool attachmentsField;

        private bool attachmentsFieldSpecified;

        public UnitReport()
        {
            this.modeField = "D";
        }

        /// <remarks/>
        public Station Station
        {
            get
            {
                return this.stationField;
            }
            set
            {
                this.stationField = value;
            }
        }

        /// <remarks/>
        public Operator Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }

        /// <remarks/>
        public Category Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        public Property Property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        /// <remarks/>
        public TestRun TestRun
        {
            get
            {
                return this.testRunField;
            }
            set
            {
                this.testRunField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("D")]
        public string mode
        {
            get
            {
                return this.modeField;
            }
            set
            {
                this.modeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnore()]
        public System.DateTimeOffset starttime
        {
            get
            {
                return this.starttimeField;
            }
            set
            {
                this.starttimeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("start-time")]
        public string starttime_text
        {
            get
            {
                return this.starttimeField.ToString("O");
            }
            set
            {
                DateTimeOffset.TryParse(value, out this.starttimeField);
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.DateTimeOffset endtime
        {
            get
            {
                return this.endtimeField;
            }
            set
            {
                this.endtimeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("end-time")]
        public string endtime_text
        {
            get
            {
                return this.endtimeField.ToString("O");
            }
            set
            {
                DateTimeOffset.TryParse(value, out this.endtimeField);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified
        {
            get
            {
                return this.quantityFieldSpecified;
            }
            set
            {
                this.quantityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("software-version")]
        public string softwareversion
        {
            get
            {
                return this.softwareversionField;
            }
            set
            {
                this.softwareversionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachments
        {
            get
            {
                return this.attachmentsField;
            }
            set
            {
                this.attachmentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentsSpecified
        {
            get
            {
                return this.attachmentsFieldSpecified;
            }
            set
            {
                this.attachmentsFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Station
    {

        private Property itemField;

        private string guidField;

        private string nameField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public Property Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Property
    {

        private object[] itemsField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValueArray", typeof(ValueArray))]
        [System.Xml.Serialization.XmlElementAttribute("ValueAttachment", typeof(ValueAttachment))]
        [System.Xml.Serialization.XmlElementAttribute("ValueBoolean", typeof(ValueBoolean))]
        [System.Xml.Serialization.XmlElementAttribute("ValueDouble", typeof(ValueDouble))]
        [System.Xml.Serialization.XmlElementAttribute("ValueInteger", typeof(ValueInteger))]
        [System.Xml.Serialization.XmlElementAttribute("ValueRecord", typeof(ValueRecord))]
        [System.Xml.Serialization.XmlElementAttribute("ValueString", typeof(ValueString))]
        [System.Xml.Serialization.XmlElementAttribute("ValueTimestamp", typeof(ValueTimestamp))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ValueArray
    {

        private object[] itemsField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValueArray", typeof(ValueArray))]
        [System.Xml.Serialization.XmlElementAttribute("ValueBoolean", typeof(ValueBoolean))]
        [System.Xml.Serialization.XmlElementAttribute("ValueDouble", typeof(ValueDouble))]
        [System.Xml.Serialization.XmlElementAttribute("ValueInteger", typeof(ValueInteger))]
        [System.Xml.Serialization.XmlElementAttribute("ValueRecord", typeof(ValueRecord))]
        [System.Xml.Serialization.XmlElementAttribute("ValueString", typeof(ValueString))]
        [System.Xml.Serialization.XmlElementAttribute("ValueTimestamp", typeof(ValueTimestamp))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ValueBoolean
    {

        private string nameField;

        private bool uslField;

        private bool uslFieldSpecified;

        private bool lslField;

        private bool lslFieldSpecified;

        private string uomField;

        private string gradeField;

        private bool valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool usl
        {
            get
            {
                return this.uslField;
            }
            set
            {
                this.uslField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uslSpecified
        {
            get
            {
                return this.uslFieldSpecified;
            }
            set
            {
                this.uslFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool lsl
        {
            get
            {
                return this.lslField;
            }
            set
            {
                this.lslField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lslSpecified
        {
            get
            {
                return this.lslFieldSpecified;
            }
            set
            {
                this.lslFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ValueDouble
    {

        private string nameField;

        private double uslField;

        private bool uslFieldSpecified;

        private double lslField;

        private bool lslFieldSpecified;

        private double udilField;

        private bool udilFieldSpecified;

        private double ldilField;

        private bool ldilFieldSpecified;

        private string uomField;

        private string gradeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double usl
        {
            get
            {
                return this.uslField;
            }
            set
            {
                this.uslField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uslSpecified
        {
            get
            {
                return this.uslFieldSpecified;
            }
            set
            {
                this.uslFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double lsl
        {
            get
            {
                return this.lslField;
            }
            set
            {
                this.lslField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lslSpecified
        {
            get
            {
                return this.lslFieldSpecified;
            }
            set
            {
                this.lslFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double udil
        {
            get
            {
                return this.udilField;
            }
            set
            {
                this.udilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool udilSpecified
        {
            get
            {
                return this.udilFieldSpecified;
            }
            set
            {
                this.udilFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ldil
        {
            get
            {
                return this.ldilField;
            }
            set
            {
                this.ldilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ldilSpecified
        {
            get
            {
                return this.ldilFieldSpecified;
            }
            set
            {
                this.ldilFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

       //[System.Xml.Serialization.XmlTextAttribute()]
       //public string Value_text
       //{
       //    get
       //    {
       //        return this.valueField.ToString("F2");
       //    }
       //    set
       //    {
       //        Double.TryParse(value, out this.valueField);
       //    }
       //}
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ValueInteger
    {

        private string nameField;

        private int uslField;

        private bool uslFieldSpecified;

        private int lslField;

        private bool lslFieldSpecified;

        private double udilField;

        private bool udilFieldSpecified;

        private double ldilField;

        private bool ldilFieldSpecified;

        private string uomField;

        private string gradeField;

        private int valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int usl
        {
            get
            {
                return this.uslField;
            }
            set
            {
                this.uslField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uslSpecified
        {
            get
            {
                return this.uslFieldSpecified;
            }
            set
            {
                this.uslFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int lsl
        {
            get
            {
                return this.lslField;
            }
            set
            {
                this.lslField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lslSpecified
        {
            get
            {
                return this.lslFieldSpecified;
            }
            set
            {
                this.lslFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double udil
        {
            get
            {
                return this.udilField;
            }
            set
            {
                this.udilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool udilSpecified
        {
            get
            {
                return this.udilFieldSpecified;
            }
            set
            {
                this.udilFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ldil
        {
            get
            {
                return this.ldilField;
            }
            set
            {
                this.ldilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ldilSpecified
        {
            get
            {
                return this.ldilFieldSpecified;
            }
            set
            {
                this.ldilFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ValueRecord
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValueBoolean", typeof(ValueBoolean))]
        [System.Xml.Serialization.XmlElementAttribute("ValueDouble", typeof(ValueDouble))]
        [System.Xml.Serialization.XmlElementAttribute("ValueInteger", typeof(ValueInteger))]
        [System.Xml.Serialization.XmlElementAttribute("ValueString", typeof(ValueString))]
        [System.Xml.Serialization.XmlElementAttribute("ValueTimestamp", typeof(ValueTimestamp))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ValueString
    {

        private string nameField;

        private string uslField;

        private string lslField;

        private string uomField;

        private string gradeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string usl
        {
            get
            {
                return this.uslField;
            }
            set
            {
                this.uslField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lsl
        {
            get
            {
                return this.lslField;
            }
            set
            {
                this.lslField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ValueTimestamp
    {

        private string nameField;

        private System.DateTime uslField;

        private bool uslFieldSpecified;

        private System.DateTime lslField;

        private bool lslFieldSpecified;

        private System.DateTime udilField;

        private bool udilFieldSpecified;

        private System.DateTime ldilField;

        private bool ldilFieldSpecified;

        private string uomField;

        private string gradeField;

        private System.DateTime valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime usl
        {
            get
            {
                return this.uslField;
            }
            set
            {
                this.uslField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uslSpecified
        {
            get
            {
                return this.uslFieldSpecified;
            }
            set
            {
                this.uslFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime lsl
        {
            get
            {
                return this.lslField;
            }
            set
            {
                this.lslField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lslSpecified
        {
            get
            {
                return this.lslFieldSpecified;
            }
            set
            {
                this.lslFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime udil
        {
            get
            {
                return this.udilField;
            }
            set
            {
                this.udilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool udilSpecified
        {
            get
            {
                return this.udilFieldSpecified;
            }
            set
            {
                this.udilFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ldil
        {
            get
            {
                return this.ldilField;
            }
            set
            {
                this.ldilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ldilSpecified
        {
            get
            {
                return this.ldilFieldSpecified;
            }
            set
            {
                this.ldilFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ValueAttachment
    {

        private string nameField;

        private string fqnField;

        private string typeField;

        private string filterField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fqn
        {
            get
            {
                return this.fqnField;
            }
            set
            {
                this.fqnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filter
        {
            get
            {
                return this.filterField;
            }
            set
            {
                this.filterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Operator
    {

        private Property itemField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public Property Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Category
    {

        private object[] itemsField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Category", typeof(Category))]
        [System.Xml.Serialization.XmlElementAttribute("Product", typeof(Product))]
        [System.Xml.Serialization.XmlElementAttribute("Property", typeof(Property))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Product
    {

        private object[] itemsField;

        private string partnoField;

        private string serialnoField;

        private string nameField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Category", typeof(Category))]
        [System.Xml.Serialization.XmlElementAttribute("Product", typeof(Product))]
        [System.Xml.Serialization.XmlElementAttribute("Property", typeof(Property))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("part-no")]
        public string partno
        {
            get
            {
                return this.partnoField;
            }
            set
            {
                this.partnoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-no")]
        public string serialno
        {
            get
            {
                return this.serialnoField;
            }
            set
            {
                this.serialnoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TestRun
    {

        private object[] itemsField;

        private string nameField;

        private System.DateTimeOffset starttimeField;

        private System.DateTimeOffset endtimeField;

        private bool endtimeFieldSpecified;

        private string versionField;

        private string gradeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error", typeof(Error))]
        [System.Xml.Serialization.XmlElementAttribute("Property", typeof(Property))]
        [System.Xml.Serialization.XmlElementAttribute("Result", typeof(Result))]
        [System.Xml.Serialization.XmlElementAttribute("SetUp", typeof(SetUp))]
        [System.Xml.Serialization.XmlElementAttribute("TestRun", typeof(TestRun))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnore()]
        public System.DateTimeOffset starttime
        {
            get
            {
                return this.starttimeField;
            }
            set
            {
                this.starttimeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("start-time")]
        public string starttime_text
        {
            get
            {
                return this.starttimeField.ToString("O");
            }
            set
            {
                DateTimeOffset.TryParse(value, out this.starttimeField);
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.DateTimeOffset endtime
        {
            get
            {
                return this.endtimeField;
            }
            set
            {
                this.endtimeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("end-time")]
        public string endtime_text
        {
            get
            {
                return this.endtimeField.ToString("O");
            }
            set
            {
                DateTimeOffset.TryParse(value, out this.endtimeField);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Error
    {

        private Message[] messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Message")]
        public Message[] Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Message
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Result
    {

        private object[] itemsField;

        private Property propertyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValueArray", typeof(ValueArray))]
        [System.Xml.Serialization.XmlElementAttribute("ValueAttachment", typeof(ValueAttachment))]
        [System.Xml.Serialization.XmlElementAttribute("ValueBoolean", typeof(ValueBoolean))]
        [System.Xml.Serialization.XmlElementAttribute("ValueDouble", typeof(ValueDouble))]
        [System.Xml.Serialization.XmlElementAttribute("ValueInteger", typeof(ValueInteger))]
        [System.Xml.Serialization.XmlElementAttribute("ValueRecord", typeof(ValueRecord))]
        [System.Xml.Serialization.XmlElementAttribute("ValueString", typeof(ValueString))]
        [System.Xml.Serialization.XmlElementAttribute("ValueTimestamp", typeof(ValueTimestamp))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        public Property Property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SetUp
    {

        private object[] itemsField;

        private Property propertyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValueArray", typeof(ValueArray))]
        [System.Xml.Serialization.XmlElementAttribute("ValueAttachment", typeof(ValueAttachment))]
        [System.Xml.Serialization.XmlElementAttribute("ValueBoolean", typeof(ValueBoolean))]
        [System.Xml.Serialization.XmlElementAttribute("ValueDouble", typeof(ValueDouble))]
        [System.Xml.Serialization.XmlElementAttribute("ValueInteger", typeof(ValueInteger))]
        [System.Xml.Serialization.XmlElementAttribute("ValueRecord", typeof(ValueRecord))]
        [System.Xml.Serialization.XmlElementAttribute("ValueString", typeof(ValueString))]
        [System.Xml.Serialization.XmlElementAttribute("ValueTimestamp", typeof(ValueTimestamp))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        public Property Property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }
}
